### ISSUE TITLE
Testing framework

### ISSUE THREAD

**Issue by elliothershberg** [GMOD/dash_jbrowse#2]
We probably need:

- integration tests for the Dash component
- unit tests for any Python/Flask code we write (pytest)
- CI for running this as GH actions

From the Dash component information:

- Write tests for your component.
    - A sample test is available in `tests/test_usage.py`, it will load `usage.py` and you can then automate interactions with selenium.
    - Run the tests with `$ pytest tests`.
    - The Dash team uses these types of integration tests extensively. Browse the Dash component code on GitHub for more examples of testing (e.g. https://github.com/plotly/dash-core-components)

**Comment by teresam856** [comment]
Ran into some issues when trying to run the tests myself...
Some notes to add to the instructions:
* need to specify dependencies on chromedriver to run dash integration tests
* need to add instructions to install that chromedriver
* need to add instructions to use another browser other than chrome
