### ISSUE TITLE
Automate builds and publishing

### ISSUE THREAD

**Issue by elliothershberg** [GMOD/dash_jbrowse#3]
This is the info for building/publishing from the Dash template:

1. Build your code:
    ```
    $ npm run build
    ```
2. Create a Python distribution
    ```
    $ python setup.py sdist bdist_wheel
    ```
    This will create source and wheel distribution in the generated the `dist/` folder.
    See [PyPA](https://packaging.python.org/guides/distributing-packages-using-setuptools/#packaging-your-project)
    for more information.

3. Test your tarball by copying it into a new environment and installing it locally:
    ```
    $ pip install dash_jbrowse-0.0.1.tar.gz
    ```

4. If it works, then you can publish the component to NPM and PyPI:
    1. Publish on PyPI
        ```
        $ twine upload dist/*
        ```
    2. Cleanup the dist folder (optional)
        ```
        $ rm -rf dist
        ```
    3. Publish on NPM (Optional if chosen False in `publish_on_npm`)
        ```
        $ npm publish
        ```
        _Publishing your component to NPM will make the JavaScript bundles available on the unpkg CDN. By default, Dash serves the component library's CSS and JS locally, but if you choose to publish the package to NPM you can set `serve_locally` to `False` and you may see faster load times._

5. Share your component with the community! https://community.plotly.com/c/dash
    1. Publish this repository to GitHub
    2. Tag your GitHub repository with the plotly-dash tag so that it appears here: https://github.com/topics/plotly-dash
    3. Create a post in the Dash community forum: https://community.plotly.com/c/dash

**Comment by teresam856** [comment]
Update: As of right now this is the only thing that is needed for the dash_jbrowse repo. 
Will add the dash_jbrowse as a dependency to this repo: https://github.com/teresam856/jbrowse-jupyter/blob/main/requirements.txt#L2.

**Comment by teresam856** [comment]
Architecture discussion:
* `dash_jbrowse`: dash component that is a wrapper to the React Linear Genome View
* `jbrowse_jupyter`: python package that includes API for creating configurations, launching dash components  in jupyter cells, indexing in the background(wishlist), local file support, integration with other bioinformatics packages
(Note: dash_jbrowse is a dependency of the jbrowse_jupyter package)

Some benefits of moving the API to another repo and making this dash component as a dependency to the jupyter jbrowse package include:
`pros`
* dash_jbrowse can be reused in other libraries
* reduces the size of dash_jbrowse for those who are not interested in the jupyter functionality
* easier to make updates to either package
* jbrowse jupyter users will only need to download one package to get all the functionality to create jbrowse components and launch them into jupyter cells
* dash_jbrowse was also created from the cookie cutter repo, so trying to differentiate the python jupyter package with the React  dash_jbrowse package can be a little confusing for contributors and maintainers.

`cons`
* more packages/repos to maintain

**Comment by teresam856** [comment]
Automate builds through github actions workflow:
Find documentation here https://github.com/pypa/gh-action-pypi-publish.
Will manually publish version 0.0.8 to Pypi

**Comment by teresam856** [comment]
Need to add a secret to this repo for automatic releases
