### ISSUE TITLE
Python class system

### ISSUE THREAD

**Issue by elliothershberg** [GMOD/dash_jbrowse#4]
Create a Python API for generating config.

High-level ideas:

- Class based, i.e. the `Config` class
- Class methods for updating config
    - `config.add_assembly('hg19.fa')`
    - etc.

Some considerations:

- Could we index things for people under the hood? For example [pysam](https://pysam.readthedocs.io/en/latest/usage.html#using-samtools-commands-within-python) for indexing and compressing? 🔥
- could we also have pre-built options, literally just do `config.add_assembly(assembly="hg38")` and do everything from there (we could have these as pre-configured, using our jbrowse s3 urls)

Some code inspiration: [vitescce-python](https://github.com/vitessce/vitessce-python)

**Comment by teresam856** [comment]
add_assembly
add_track
set_location
set_session

**Comment by teresam856** [comment]
add_assembly(
file = `index.fa`,
index = NULL 
)

if no index, it gets generated w/ pysam

**Comment by teresam856** [comment]
Architecture discussion:

The jbrowse_jupyter repo will contain the python class system to build Jbrowse2 embedded LGV configuration objects.
Just like JbrowseR, this class system will work something like this in a jupyter notebook

```
jbrowse_conf = JBrowseConfig()

// pass aliases
aliases = ["hg38"]
// pass refName aliases
ref_name_aliases = {
        "adapter": {
            "type": "RefNameAliasAdapter",
            "location": {
                "uri": "https://s3.amazonaws.com/jbrowse.org/genomes/GRCh38/hg38_aliases.txt",
                "locationType": "UriLocation",
            },
        },
    }

// set the assembly with a fasta file and whether it is gz or not
jbrowse_conf.set_assembly("https://jbrowse.org/genomes/GRCh38/fasta/hg38.prefix.fa.gz", aliases, ref_name_aliases, True)

// obtain the config and launch the view
config = jbrowse_conf.get_config()
jb2_config_view = create_jbrowse('config', config=config)
launch_jbrowse(jb2_config_view)
```

**Comment by teresam856** [comment]
closing issue and moving to https://github.com/teresam856/jbrowse-jupyter
