### ISSUE TITLE
Warning from PyPI on latest release

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/dash_jbrowse#42]
text of email

### Email

<div class="aju"><div class="aCi"><img id=":o6_5-e" name=":o6" src="https://lh3.googleusercontent.com/a/default-user=s40-p" class="ajn" style="background-color: #cccccc" jid="noreply@pypi.org" data-hovercard-id="noreply@pypi.org" data-name="PyPI" aria-hidden="true"></div></div><div class="gs"><div class="gE iv gt">

PyPI <noreply@pypi.org> | PyPI <noreply@pypi.org> | 10:12 AM (1 hour ago)
-- | -- | --
PyPI <noreply@pypi.org>

PyPI <noreply@pypi.org>
	
10:12 AM (1 hour ago)
	
to me
What?

During a recent upload of dash-jbrowse to PyPI, we noticed you uploaded an .egg/bdist_egg distribution file.

PyPI is in the process of deprecating bdist_egg distribution file uploads, and will not accept them beginning August 1, 2023.
What should I do?

Update your release tooling to cease upload of .egg/bdist_egg distribution files. If you are not already, and require binary releases, update your release tooling to upload .whl/bdist_wheel distribution files instead.

Read more about [Wheels vs Egg](https://packaging.python.org/en/latest/discussions/wheel-vs-egg/) distribution files.

**Comment by teresam856** [comment]
Yeah we may need to update the setup to a pyproject.toml. Egg files are
deprecated and we are using legacy bdist to build the package.

1) replace setup.py with pyproject.toml
2) update the pipeline to use python -m build instead of running python
setup.py bdist
3) make sure twine is only uploading the wheel or tar generated

**Comment by cmdcolin** [comment]
I think it's now past the august 1,2023 deadline and so we gotta try to update this

**Comment by cmdcolin** [comment]
super thanks to @hexylena for helping on gitter. PR https://github.com/GMOD/dash_jbrowse/pull/45 added the change to `python -m build`. It also runs against TestPyPI on branch pushes now
